### PR TITLE
Experimental

### PR DESCRIPTION
**Pull request by awareness481**
Opening this to keep track of progress & potential reviews.

### CODE REVIEW

**Review by momegas — APPROVED** [review]
Looks nice to me :)

**Comment by awareness481** [comment]
Sure, if we merge we should use `squash and merge`

**Comment by momegas** [comment]
> Sure, if we merge we should use `squash and merge`

Should i merge or will you?

**Comment by awareness481** [comment]
> > Sure, if we merge we should use `squash and merge`
> 
> Should i merge or will you?

I was expecting you to merge but if you dont feel comfortable because there are a lot of changes I can do it

**Comment by momegas** [comment]
> > > Sure, if we merge we should use `squash and merge`
> > 
> > 
> > Should i merge or will you?
> 
> I was expecting you to merge but if you dont feel comfortable because there are a lot of changes I can do it

You can merge it because I guess it needs testing beyond just looking at the code. Btw it has conflicts. Do your thing, I trust your judgement 😉

**Pull request merged**
